config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  # test
  get "map", to: "map#show"
  #root "rentals#new"
  
  
  #get "/stations/:identification", to: "stations#main"
  get "stations", to: "stations#main", as:"stations"
  get "add_stations", to: "stations#new"
  post "stations", to: "stations#create"
  #get "/stations/:identifier", to: "station#reverse", as: "station_rev"

  # hsm mods
  get "/bikes/unlock", to: "bikes#unlock"
  get "add_bikes", to: "bikes#new"
  post "bikes", to: "bikes#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  get "user_home", to: "users#show"
  post 'login', to: 'sessions#create'

  get "bikes_unlock", to: "bikes#unlock"


  #delete "logout", to: "sessions#destroy"

  get "/logout", to: "sessions#destroy"


  get '/users/:id', to: 'users#menu', as: 'user'
  get "user/show"
  
  # payment page info
  #get "payment", to:'payment#new' # testing
  get "bikes", to: "bikes#index" # testing 

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  get '/reports/success', to: "reports#success"
  get '/reports/empty', to: "reports#empty"
  get 'return', to: 'rentals#return'
  match'ride',to:"bikes#index", via: :get
  get '/bikes/return', to: "bikes#return"
  resources :bikes, only: [:index]
  resources :stations, only: [:main, :show]
  resources :users, except: [:new]
  resources :rentals, only: [:new, :create]
  resources :rentals, only: [:return]
  resources :reports, only: [:new, :create]

  get "report_home", to: "reports#index"

  #resources :payment, only: [:new, :edit]

  get "rename", to: "username#edit", as: :edit_username
  post "rename", to: "username#update"

  get "change_address", to: "address#edit", as: :edit_address
  patch "change_address", to: "address#update"

  get "change_wallet", to: "wallet#edit", as: :edit_wallet
  post "change_wallet", to: "wallet#update"

  get "payment", to: "payment#edit", as: :payment
  post "payment", to: "payment#update"


  get "change_blocking", to: "blocking#edit", as: :edit_blocking
  post "change_blocking", to: "blocking#update"
  
  get "change_phonenum", to: "phonenum#edit", as: :edit_phone
  patch "change_phonenum", to: "phonenum#update"



end

app/models/station.rb
class Station < ApplicationRecord
  validates_presence_of    :identifier,
                           :name,
                           :address,
                           :longitude,
                           :latitude
  validates_uniqueness_of  :identifier

  has_many :docked_bikes, class_name: :Bike,  foreign_key: :current_station_id
  
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  
  def index
    @stations = Station.all.order(identifier: :asc)
  end
  
  def reverse
    @stations = Station.all.order(identifier: :desc)
  end
  
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_reverse.html.erb
# i think i can get rid of this entire file

<%= form_with model: station do |reverse| %>
    <div>
        <%= reverse.label :title %>
    </div>

    <div>
        <%= reverse.submit %>
    </div>
<% end %>

app/views/stations/_row.html 2.erb
<div class="record-row <%= cycle "odd", "even", name: "row-cycler" %> flexbox vertical stretch">
  <%= station.identifier %>: <%= station.name %> (<%= station.address %>)
</div>

app/views/stations/_row.html.erb
<div class="record-row <%= cycle "odd", "even", name: "row-cycler" %> flexbox horizontal justify-space-between">
  <div><%= station.identifier %>: <%= station.name %> (<%= station.address %>)</div>
  <div><% station.docked_bikes.count %> </div>
  <h4 style="color:#0CCAA8;text-align:center;"><%=link_to('select station', station_path(station.identifier)) %></h4>
</div>

app/views/stations/index.html 2.erb
<div class="page-section flexbox vertical stretch">
  <div class="section-inner flexbox vertical stretch">
    <div class="section-title">
      Welcome to ValetBike, the bike finding app!
    </div>  
    <div class="flexbox vertical stretch">
      <% if @stations.present? %>
        <%= render(partial: "stations/row", collection: @stations, as: :station) %>
      <% else %>
      <div class="empty">
        No stations found.
      </div>
      <% end %>
    </div>
	</div>
</div>

app/views/stations/index.html.erb
<div class="page-section flexbox vertical stretch">
  <div class="section-inner flexbox vertical stretch">

    <div class="section-title flexbox horizontal center">
      Welcome to bikesia!
      <a class="toggle" href="<%= bikes_path %>">View Bike Fleet</a>
    </div>  

    <div class="flexbox vertical stretch">
      <% if @stations.present? %>
      <% @stations.each do |s|%>
      <%=link_to('select station', {controller: 'bikes', action: 'index'}) %>
       <%= render(partial: "stations/row", collection: @stations, as: :station) %>
       
       <%end%>
      <% else %>
      <div class="empty">
        No stations found.
      </div>
      <% end %>

      <div class="rights-text">
      <br></br>
      2023 Version 01 CSC 223-01
      </div>  

    </div>
  </div>
</div>

app/views/stations/main.html.erb
<div class="page-section flexbox vertical stretch">
  <div class="section-inner flexbox vertical stretch">

    <div class="section-title flexbox horizontal center">
      <h2> Welcome to bikesia! </h2>
      <a class="toggle" href="<%= bikes_path %>">View Bike Fleet</a>
      <a class="toggle" href="<%= root_path %>">Home page</a> 
    </div>  

    <div class="flexbox vertical stretch">
      <% if @stations.present? %>
       <%= render(partial: "stations/row", collection: @stations, as: :station) %>
      
      <% else %>
      <div class="empty">
        No stations found.
      </div>
      <% end %>

      <div class="rights-text">
      <br></br>
      2023 Version 01 CSC 223-01
      </div>  

    </div>
  </div>
</div>

app/views/stations/show.html.erb
<h1><%=@station.name%></h1>

<ul>
<% @station.docked_bikes.each do |bike| %>
<li><%= bike.identifier%> 
<%=link_to('unlock bike', new_rental_path(bike.identifier))%>
</li>
<%end%>
</ul>