config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  # test
  get "map", to: "map#show"
  #root "rentals#new"
  
  
  #get "/stations/:identification", to: "stations#main"
  get "stations", to: "stations#main", as:"stations"
  get "add_stations", to: "stations#new"
  post "stations", to: "stations#create"
  #get "/stations/:identifier", to: "station#reverse", as: "station_rev"

  # hsm mods
  get "/bikes/unlock", to: "bikes#unlock"
  get "add_bikes", to: "bikes#new"
  post "bikes", to: "bikes#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  get "user_home", to: "users#show"
  post 'login', to: 'sessions#create'

  get "bikes_unlock", to: "bikes#unlock"


  #delete "logout", to: "sessions#destroy"

  get "/logout", to: "sessions#destroy"


  get '/users/:id', to: 'users#menu', as: 'user'
  get "user/show"
  
  # payment page info
  #get "payment", to:'payment#new' # testing
  get "bikes", to: "bikes#index" # testing 

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  get '/reports/success', to: "reports#success"
  get '/reports/empty', to: "reports#empty"
  get 'return', to: 'rentals#return'
  match'ride',to:"bikes#index", via: :get
  get '/bikes/return', to: "bikes#return"
  resources :bikes, only: [:index]
  resources :stations, only: [:main, :show]
  resources :users, except: [:new]
  resources :rentals, only: [:new, :create]
  resources :rentals, only: [:return]
  resources :reports, only: [:new, :create]

  get "report_home", to: "reports#index"

  #resources :payment, only: [:new, :edit]

  get "rename", to: "username#edit", as: :edit_username
  post "rename", to: "username#update"

  get "change_address", to: "address#edit", as: :edit_address
  patch "change_address", to: "address#update"

  get "change_wallet", to: "wallet#edit", as: :edit_wallet
  post "change_wallet", to: "wallet#update"

  get "payment", to: "payment#edit", as: :payment
  post "payment", to: "payment#update"


  get "change_blocking", to: "blocking#edit", as: :edit_blocking
  post "change_blocking", to: "blocking#update"
  
  get "change_phonenum", to: "phonenum#edit", as: :edit_phone
  patch "change_phonenum", to: "phonenum#update"



end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true
    validates :email, presence: true
    validates :password, presence: true

    validates_uniqueness_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user =User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            if @user.email = "bikesia@example.com"
                @user.admin = true
                @user.save
            end
            session[:user_id] = @user.id
            session[:username] = @user.username
            flash[:notice] = "User created."
            redirect_to root_path(@user)
        else
            render 'new'
        end
    
    end


    def edit
        if logged_in?
            redirect_to login_path
         else
            #let them change the mode
        end
    
    end

    def show
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
        # if session[:username]
        #      @user = User.find(session[:username])
        # end
        # if logged_in?
        #     redirect_to user_home_path
        #  else
        #     redirect_to login_path
        # end
        #@username =cookies[:username]
        #@user = User.find params.require(:id)
        #@user = User.find(params[:id])
        #@username =cookies[:username]
    end
     
    private
 
    def user_params
        params.require(:user).permit(:username, :email, :password, :phone_num, :address, :birthday, :wallet_point, :default_payment)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create_user.html.erb
<h1>Sign up</h1>
<%= form_with(model: @user, local: true) do |f| %>
 
<div class="form-group">
  <%= f.label :username %><br/>
  <%= f.text_field :username, class: "form-control" %>
</div>
 
<%# <div class="form-group">
  <%# <%= f.label :email %>
  <%# <%= f.email_field :email, class: "form-control" %>
<%# </div> %> 

<div class="form-group">
  <%= f.label :password %><br/>
  <%= f.password_field :password, class: "form-control" %>
</div>
 
<div class="form-group">
  <%= f.submit %>
</div>
 
<% end %>

app/views/users/new.html.erb
<h2>Sign up</h2>
<%= form_with(model: @user, local: true) do |f| %>
 
<div class="form-group">
  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control" %>
</div>

<br/>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
</div>

<br/>
<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
</div> 

<br/>
<div class="form-group">
  <%= f.label :phone_num %>
  <%= f.text_field :phone_num, class: "form-control" %><br/>
</div> 
<br/>

<div class="form-group">
  <%= f.label :address %> 
  <%= f.text_field :address, class: "form-control" %><br/>
</div> 
<br/>
<div class="form-group">
  <%= f.label :birthday %> 
  <%= f.date_field :birthday, class: "form-control" %><br/>
</div>
<br/>
<br/>
<div class="form-group">
  <%= f.label :default_payment %> 
  <%= f.text_field :default_payment, class: "form-control" %><br/>
</div>

<br/>

<div class="form-group">
  <%= f.submit %>
</div>
 
<% end %>
<a class="toggle" href="<%= root_path %>">&emsp; Return to Homepage</a>

app/views/users/report.html.erb
Report an Issue
</br>
Please email your current issue to test@example.com

app/views/users/show.html.erb
<div  class = "user index"> 
    <h2>User Profile</h2>

    <% if @user %>
         <% if @user. admin == true%>
            <h3> Hi Admin! What do you want to next? </h3>
            <h3> <%= link_to("Add Blocking list", edit_blocking_path)%> </h3 >
            <h3> <%= link_to("Add Station", add_stations_path)%> </h3>
            <h3> <%= link_to("Add Bike", add_bikes_path)%> </h3>
            <br> <br>
        <%end%>
            <h3> User information </h3>
            Logged in as: <b><%= @user.username %> </b> <br>
            <h4 style="color:#0CCAA8;text-align:center;"><%= link_to("Edit username", edit_username_path) %></h4>

            <h4 style="color:#0CCAA8;text-align:center;"><%= link_to("Change password", edit_password_path) %></h4>
        
            Email: <b><%= @user.email %></b><br>
            
            Home address: <b><%= @user.address %></b><br> 
            <h4 style="color:#0CCAA8;text-align:center;"><%= link_to("Edit address", edit_address_path, class: "link") %></h4>
            
            Birthday: <b><%= @user.birthday %></b><br>


            Wallet points: <b><%= @user.wallet_point%></b><br>
            <h4 style="color:#0CCAA8;text-align:center;"><%= link_to("Edit wallet point", edit_wallet_path) %><br> </h4>
    <%else%>
        You haven't logged in. Please log in to see your user profile. 
        <%= link_to("Click here", login_path) %>
    <% end %>
    
</div>