config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  # test
  get "map", to: "map#show"
  #root "rentals#new"
  
  
  #get "/stations/:identification", to: "stations#main"
  get "stations", to: "stations#main", as:"stations"
  get "add_stations", to: "stations#new"
  post "stations", to: "stations#create"
  #get "/stations/:identifier", to: "station#reverse", as: "station_rev"

  # hsm mods
  get "/bikes/unlock", to: "bikes#unlock"
  get "add_bikes", to: "bikes#new"
  post "bikes", to: "bikes#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  get "user_home", to: "users#show"
  post 'login', to: 'sessions#create'

  get "bikes_unlock", to: "bikes#unlock"


  #delete "logout", to: "sessions#destroy"

  get "/logout", to: "sessions#destroy"


  get '/users/:id', to: 'users#menu', as: 'user'
  get "user/show"
  
  # payment page info
  #get "payment", to:'payment#new' # testing
  get "bikes", to: "bikes#index" # testing 

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  get '/reports/success', to: "reports#success"
  get '/reports/empty', to: "reports#empty"
  get 'return', to: 'rentals#return'
  match'ride',to:"bikes#index", via: :get
  get '/bikes/return', to: "bikes#return"
  resources :bikes, only: [:index]
  resources :stations, only: [:main, :show]
  resources :users, except: [:new]
  resources :rentals, only: [:new, :create]
  resources :rentals, only: [:return]
  resources :reports, only: [:new, :create]

  get "report_home", to: "reports#index"

  #resources :payment, only: [:new, :edit]

  get "rename", to: "username#edit", as: :edit_username
  post "rename", to: "username#update"

  get "change_address", to: "address#edit", as: :edit_address
  patch "change_address", to: "address#update"

  get "change_wallet", to: "wallet#edit", as: :edit_wallet
  post "change_wallet", to: "wallet#update"

  get "payment", to: "payment#edit", as: :payment
  post "payment", to: "payment#update"


  get "change_blocking", to: "blocking#edit", as: :edit_blocking
  post "change_blocking", to: "blocking#update"
  
  get "change_phonenum", to: "phonenum#edit", as: :edit_phone
  patch "change_phonenum", to: "phonenum#update"



end

app/models/bike.rb
class Bike < ApplicationRecord
  validates_presence_of    :identifier
                           #:current_station_identifier,
                           #:station_id
 
  validates_uniqueness_of  :identifier


  belongs_to :current_station, class_name: :Station, foreign_key: :current_station_id, optional: true

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController

  def index
       if params[:reverse].blank? || params[:reverse]=="0"
            @bikes = Bike.all.order(identifier: :asc)
       else
            @bikes = Bike.all.order(identifier: :desc)
       end
  end

  def unlock
     if session[:user_id]
          @user = User.find(session[:user_id])
      end
  end

end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/_row.html.erb
<div class="record-row <%= cycle "odd", "even", name: "row-cycler" %> flexbox horizontal justify-space-between">
  <div><%= bike.identifier %> : <%= bike.current_station.nil? ? "Not currently in any station" : bike.current_station.name %> </div>

  <div><%= bike.current_station.blank? ?  "In Use" : bike.current_station.address %></div>
</div>

app/views/bikes/index.html.erb
<div class="page-section flexbox vertical stretch"> 
  <div class="section-inner flexbox vertical stretch"> 
    <div class="section-title flexbox horizontal center">
      Meet the Bikesia Fleet!
      <a class="toggle" href="<%= payment_path %>">Payment page</a>
      <a class="toggle" href="<%= stations_path %>">View Stations</a> 
      <a class="toggle" href="<%= root_path %>">Home page</a> 
    </div>
    <div class="flexbox vertical stretch">
      <% if @bikes.present? %>
        <div class="record-row header flexbox horizontal justify-space-between">
          <% if params[:reverse].blank? || params[:reverse] == "0" %>
            <a href="<%= bikes_path(params: {reverse: 1})%>">Sort :desc</a>
          <% else %>
            <a href="<%= bikes_path %>">Sort :asc</a> 
          <% end %>
        </div>
        <%= render(partial: "bikes/row", collection: @bikes, as: :bike) %>
      <% else %>
      <div class="empty">
        No bikes found.
      </div>
      <% end %> 
    </div>
  </div> 
</div>

app/views/bikes/return.html.erb
<h1>Your bike has successfully been returned</h1>
<h3><%=link_to('Go back to Homepage', root_path)%><h3>

app/views/bikes/unlock.html.erb
<h1>Your bike has successfully been unlocked</h1>
<h1> Now ride like you can fly!!!<h1>
<h3><%=link_to('Go back to Homepage', root_path)%><h3>

<h3> Your remaining wallet point is <%= @user.wallet_point %><h3>
<% $bike= params[:format] %>
<%=link_to('return', return_path($bike))%>