config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  # test
  get "map", to: "map#show"
  #root "rentals#new"
  
  
  #get "/stations/:identification", to: "stations#main"
  get "stations", to: "stations#main", as:"stations"
  get "add_stations", to: "stations#new"
  post "stations", to: "stations#create"
  #get "/stations/:identifier", to: "station#reverse", as: "station_rev"

  # hsm mods
  get "/bikes/unlock", to: "bikes#unlock"
  get "add_bikes", to: "bikes#new"
  post "bikes", to: "bikes#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  get "user_home", to: "users#show"
  post 'login', to: 'sessions#create'

  get "bikes_unlock", to: "bikes#unlock"


  #delete "logout", to: "sessions#destroy"

  get "/logout", to: "sessions#destroy"


  get '/users/:id', to: 'users#menu', as: 'user'
  get "user/show"
  
  # payment page info
  #get "payment", to:'payment#new' # testing
  get "bikes", to: "bikes#index" # testing 

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"
  get '/reports/success', to: "reports#success"
  get '/reports/empty', to: "reports#empty"
  get 'return', to: 'rentals#return'
  match'ride',to:"bikes#index", via: :get
  get '/bikes/return', to: "bikes#return"
  resources :bikes, only: [:index]
  resources :stations, only: [:main, :show]
  resources :users, except: [:new]
  resources :rentals, only: [:new, :create]
  resources :rentals, only: [:return]
  resources :reports, only: [:new, :create]

  get "report_home", to: "reports#index"

  #resources :payment, only: [:new, :edit]

  get "rename", to: "username#edit", as: :edit_username
  post "rename", to: "username#update"

  get "change_address", to: "address#edit", as: :edit_address
  patch "change_address", to: "address#update"

  get "change_wallet", to: "wallet#edit", as: :edit_wallet
  post "change_wallet", to: "wallet#update"

  get "payment", to: "payment#edit", as: :payment
  post "payment", to: "payment#update"


  get "change_blocking", to: "blocking#edit", as: :edit_blocking
  post "change_blocking", to: "blocking#update"
  
  get "change_phonenum", to: "phonenum#edit", as: :edit_phone
  patch "change_phonenum", to: "phonenum#update"



end

app/models/report.rb
class Report < ApplicationRecord
    validates :description, presence: true
    attr_accessor :description
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    def new
        @report = Report.new
    end

    def create
       if report_params= " "
        redirect_to '/reports/empty'
      else
        @report = Report.new(report_params)
        if @report.save
          redirect_to '/reports/success', notice: "Issue reported successfully."
        else
          render :new
        end
      end
    end
    
    def index
      @reports = Report.all
    end
    
    private
    
    def report_params
        params.require(:report).permit(:title, :description)
    end

end

app/views/reports/index.html.erb
<div class="page-section flexbox vertical stretch"> 
  <div class="section-inner flexbox vertical stretch"> 
    <div class="section-title flexbox horizontal center">
      <h2>User Reports!</h2>
    <%if Current.user.admin%>
    </div> 
        <table>
          <tr>
              <h3><th>Description </th> </h3>            
          </tr>
          <% @reports.each do |report| %>
            <tr>
              <p><td><%= report.description%></td></p>        
            </tr>
          <% end %>
        </table>
    </div> 
    <%else%>
      You don't have the right to view this.
      <a class="toggle" href="<%= root_path %>">&emsp; Return to Homepage</a>
    <%end%>
</div>

app/views/reports/new.html.erb
<br>
<h2> Make a Report </h2>
<h3> See something that could be improved? <br>
Say something to our harworking team! </h3>
<br>
<%= form_with(model: @report, url: reports_path) do |form| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>
      <ul>
        <% @report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>
<%if Current.user.admin%>
  <a class="toggle" href="<%= report_home_path %>">&emsp; View Reports</a>
<%end%>
<a class="toggle" href="<%= root_path %>">&emsp; Return to Homepage</a>